apiVersion: v1
kind: Service
metadata:
  name: lottery-ui
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30801  # Custom NodePort (optional)
  selector:
    app: lottery-ui
